### ISSUE TITLE
How to install this extension?

### ISSUE THREAD

**Issue by lyrixx** [TwilightTechie/Linux-Perf-Tool-Gecko#1]
Hello, 

Could you provider installation instructions? 

Thanks

**Comment by TwilightTechie** [comment]
Hi @lyrixx 
Its already available from linux kernel 6.6, you can use it. Here you will find more details. 
[perf-wiki](https://perf.wiki.kernel.org/index.php/Tutorial#Firefox_Profiler)

let me know if you still have any issue, happy to chat

**Comment by lyrixx** [comment]
okay, I'll have to wait a bit I guess!
>Linux gregoire 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Thanks !
